### ISSUE TITLE
write the story

### ISSUE THREAD

**Issue by Noratrieb** [Nilstrieb/very-cool-amazing-heartwarming-text-adventure-story#1]

**Comment by ConnysCode** [comment]
warum <img src="https://cdn.discordapp.com/emojis/879106969431056444.png?size=16"/>

**Comment by Noratrieb** [comment]
![image](https://user-images.githubusercontent.com/48135649/144984379-b3e6192f-216c-40e4-9eea-df9b6b46beba.png)

**Comment by Noratrieb** [comment]
wontfix

**Comment by ConnysCode** [comment]
<img src="https://cdn.discordapp.com/emojis/879106969431056444.png?size=256"/>

**Comment by Noratrieb** [comment]
genau
